spring:
  datasource:
    url: jdbc:TAOS-RS://10.152.160.183:6041/gt_iot?user=root&password=taosdata&timezone=Asia/Beijing&charset=utf-8
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      validation-query: select server_status();

mybatis:
  type-aliases-package: gt.iot.wlw.flink.entity
  mapper-locations: classpath:dao/*.xml
